spring.application.name=tems

spring.datasource.url=jdbc:mysql://localhost:3306/tems_db
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


stripe.secret.key=YOUR_STRIPE_KEY
stripe.webhook.secret=YOUR_WEBHOOK_KEY